name: 'Terraform composite github actions'
description: 'Custom composite action for Terraform build'
inputs:
  deploy-plan:  # id of input
    description: 'apply -auto-approve | plan'
    required: true
  terraform_version:  # id of input
    description: 'Terraform version to be used'
    default: "1.11.3"  
  environment_stage:
    description: 'stage of deployment'
    required: false
runs:
  using: "composite"
  steps:                
    - name:  Terraform ${{ inputs.deploy-plan }}.
      run: |
             curl https://releases.hashicorp.com/terraform/${{ inputs.terraform_version }}/terraform_${{ inputs.terraform_version }}_linux_amd64.zip -O -J -L
             unzip terraform_${{ inputs.terraform_version }}_linux_amd64.zip && rm terraform_${{ inputs.terraform_version }}_linux_amd64.zip
             chmod 777 -R *        
             ./terraform init
             ./terraform validate
             ./terraform ${{ inputs.deploy-plan }}
      shell: bash