name: 'Terraform composite github actions'
description: 'Custom composite action for Terraform build'
inputs:
  aws-role:  # id of input
    description: 'Role to be used'
    required: true
  deploy-plan:  # id of input
    description: 'apply -auto-approve | plan'
    required: true
  runner_token:  # id of input
    description: 'token to be used'
    required: true
  terraform_version:  # id of input
    description: 'Terraform version to be used'
    default: "1.11.3"  
  environment_stage:
    description: 'stage of deployment'
    required: false
runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: terraformdeploysession
        aws-region: "ap-southeast-1"                   
    - name:  Terraform ${{ inputs.deploy-plan }}.
      run: |
             curl https://releases.hashicorp.com/terraform/${{ inputs.terraform_version }}/terraform_${{ inputs.terraform_version }}_linux_amd64.zip -O -J -L
             unzip terraform_${{ inputs.terraform_version }}_linux_amd64.zip && rm terraform_${{ inputs.terraform_version }}_linux_amd64.zip
             chmod 777 -R *        
             ./terraform init
             ./terraform validate
             ./terraform ${{ inputs.deploy-plan }}
      shell: bash